# .github/workflows/update-data.yml
name: Atualizar Dados dos Focos de Calor

on:
  schedule:
    # Executa a cada 60 minutos
    - cron: '0 * * * *'
  workflow_dispatch: # Permite execução manual
  push:
    branches: [ main ] # Executa também no push

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependências
      run: npm install
      
    - name: Baixar dados do Google Drive
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        SHAPEFILE_FOLDER_ID: ${{ secrets.SHAPEFILE_FOLDER_ID }}
      run: node scripts/fetch-data.js
      
    - name: Processar dados espaciais
      run: node scripts/process-spatial-data.js
      
    - name: Atualizar arquivos processados
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/data/processed/
        git diff --staged --quiet || git commit -m "🔄 Dados atualizados automaticamente - $(date)"
        
    - name: Push mudanças
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
    - name: Deploy para GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
